// <auto-generated/>
global using global::System;
global using global::System.Drawing;
global using global::System.Windows.Forms;
using System.Diagnostics;

namespace SimpleCalculator
{
    

    internal static class Program
    {
        public static double num;
        public static double num1 = double.NaN;
        public static double num2 = double.NaN;
        public static string operate;
        public static bool final = false;

        [STAThread]
        static void Main(string[] args)
        {
            ApplicationConfiguration.Initialize();
            Form1 mainForm = new Form1();
            mainForm.Size = new Size(540, 520);
            mainForm.FormBorderStyle = FormBorderStyle.FixedSingle;
            mainForm.MaximizeBox = false;


            TextBox textBox1 = new TextBox();
            textBox1.Multiline = true;
            textBox1.Font = new Font("Arial", 20);
            textBox1.Size = new System.Drawing.Size(width: 500, height: 50);
            textBox1.Location = new System.Drawing.Point(x: 10, y: 0);

            //numbers
            for (int i = 1; i < 10; i++)
            {
                makeButton(mainForm, textBox1, Convert.ToString(i), x: 10+100*((i-1)%3), y: 60+100* ((i - 1) / 3));
            }

            //zero, point and sign
            makeButton(mainForm, textBox1,"0", width: 100, x: 110, y: 360);
            makeButton(mainForm, textBox1, ".", width: 100, x: 210, y: 360);
            makeButton(mainForm,textBox1, "+/-", width: 100, x: 10, y: 360);

            //operation buttons
            makeButton(mainForm, textBox1, "Del", width: 100, x: 310, y: 60);
            makeButton(mainForm, textBox1, "AC", width: 100, x: 410, y: 60);
            makeButton(mainForm, textBox1, "+", width: 100, x: 310, y: 160);
            makeButton(mainForm, textBox1, "-", width: 100, x: 410, y: 160);
            makeButton(mainForm, textBox1, "x", width: 100, x: 310, y: 260);
            makeButton(mainForm, textBox1,  "/", width: 100, x: 410, y: 260);
            makeButton(mainForm, textBox1, "=", width: 200, x: 310, y: 360);

            mainForm.Controls.Add(textBox1);

            mainForm.Text = "Calculator App";
            Application.Run(mainForm);  

        }

        static void click(TextBox textBox, string input)
        {

            switch (input)
            {
                case "=":
                    try
                    {
                        if (!double.IsNaN(num1))
                        {
                            textBox.SelectAll();
                            num2 = Convert.ToDouble(textBox.SelectedText);
                            num1 = result(num1, num2, operate);
                            textBox.Text = Convert.ToString(num1);
                            num1 = double.NaN;
                            num2 = double.NaN;
                            final = true;
                        }

                    }
                    catch (FormatException e) { }
                    
                    break;
                case "1":
                case "2":
                case "3":
                case "4":
                case "5":
                case "6":
                case "7":
                case "8":
                case "9":
                    if (final == true)
                    {
                        textBox.Clear();
                        num1 = double.NaN;
                        num2 = double.NaN;
                    }

                    string previous = textBox.Text;
                    textBox.Text = previous + Convert.ToString(input);
                    final = false;
                    break;
                case "0":
                    if (textBox.Text == "0")
                    {
                        break;
                    }
                    textBox.SelectAll();
                    string zero = textBox.SelectedText;
                    textBox.Text = zero + Convert.ToString(input);
                    final = false;
                    break;
                case "+/-":
                    if (string.IsNullOrEmpty(textBox.Text))
                    {
                        textBox.Text = "-";
                        final = false;

                    }
                    else if (Convert.ToString((textBox.Text)[0]) == "-")
                    {
                        textBox.SelectAll();
                        string orig = textBox.SelectedText;
                        string remain = orig.Substring(1, orig.Length - 1);
                        textBox.Text = remain;
                        final = false;
                    }
                    else
                    {
                        textBox.SelectAll();
                        string orig = textBox.SelectedText;
                        textBox.Text = "-" + orig;
                    }
                    break;
                case ".":
                    string point = textBox.Text;
                    if(string.IsNullOrEmpty(textBox.Text))
                    {
                        textBox.Text = "0.";
                        final = false;

                    }
                    else if(point.Contains(".")){
                        break;
                    }
                    else
                    {
                        textBox.SelectAll();
                        textBox.Text = point + Convert.ToString(input);
                    }
                    break;
                case "Del":
                    textBox.SelectAll();
                    if (textBox.SelectedText == "0.")
                    {
                        textBox.Text = "";

                    }
                    else if (!(string.IsNullOrEmpty(textBox.Text)))
                    {
                        textBox.SelectAll();
                        string orig = textBox.SelectedText;
                        string remain = orig.Substring(0, orig.Length - 1);
                        Console.WriteLine(remain);
                        textBox.Text = remain;
                    }
                    break;
                case "AC":
                    num1 = double.NaN;
                    num2 = double.NaN;
                    textBox.Clear();
                    break;
                case "+":
                case "-":
                case "x":
                case "/":
                    final = false;
                    if (double.TryParse(textBox.Text, out num))
                    {
                        textBox.SelectAll();
                        if (double.IsNaN(num1))
                        {
                            num1 = Convert.ToDouble(textBox.SelectedText);
                            textBox.Text = "";
                            operate = input;
                        }
                        else
                        {
                            num2 = Convert.ToDouble(textBox.SelectedText);
                            textBox.Text = "";
                            num1 = result(num1, num2, operate);
                            num2 = double.NaN;
                        }

                        operate = input;
                    }
                    break;

            }  
            
        }

        static double result(double num1, double num2, string operate)
        {
            switch (operate)
            {
                case "+":
                    return num1+num2;
                case "-": 
                    return num1-num2;
                case "x":
                    return num1*num2;
                case "/":
                    return num1/num2;
                default:
                    return double.NaN;

            }


        }

        static void makeButton(Form1 main, TextBox textBox, string input, int height = 100, int width = 100, int x = 0, int y = 0)
        {
            Button button = new Button();
            button.Text = input;
            button.Size = new System.Drawing.Size(width, height);
            button.Location = new System.Drawing.Point(x, y);
            button.Click += (sender, e) => click(textBox, input);
            
            main.Controls.Add(button);
        }
    }
    
}


